### ISSUE TITLE
Character does not aloways move after migrating to new version

### ISSUE THREAD

**Issue by Person-93** [idanarye/bevy-tnua#96]
Sometimes the character does not move at all. Restarting the games sometimes fixes the issue and sometimes causes it. I'm having trouble making a minimal reproduction of the issue.

Old versions:
```toml
bevy = "0.15.3"
bevy_rapier2d = "0.28.0"
bevy-tnua = "0.21.0"
bevy-tnua-rapier2d = "0.9.0"
```
New versions:
```toml
bevy = "0.15.3"
bevy_rapier2d = "0.29.0"
bevy-tnua = "0.22.0"
bevy-tnua-rapier2d = "0.10.0"
```
